### ISSUE TITLE
Name "Solide" may lead to confusion?

### ISSUE THREAD

**Issue by brillout** [magne4000/solide#3]
@cyco130 thinks that "Solide" could be confusing, e.g. someone may thinks it's a typo.

Thoughts?

At the beginning Solide *will* be confusing, but in the long term the confusion *will* go away. It could be worth to "take the bullet".

**Comment by magne4000** [comment]
> someone may thinks it's a typo

True, but I say let's see if other people are complaining about this, because I'm not sure that's an actual issue. For now I think it's a good name (until someone finds a better one?)

**Comment by brillout** [comment]
Sounds like a good plan to me 👍.
